added a publish step and configured pom.xml file
Laserfiche/lf-api-client-core-java pull request #26
Opened 2022-07-12 17:55 UTC by sxu1998

https://v-dev-tfs/DefaultCollection/Server%20Tools/_workitems/edit/386399

2022-07-13 15:36 UTC, lf-jason-jia requested changes
Minor stuff but would be nice if we can fix:
A lot of changes are really just indentation changes. Is this intentional? If not, can we keep whatever we had before so that the git history won't get overwritten for trivial indentation changes?

2022-07-13 15:41 UTC, sxu1998 commented
> Minor stuff but would be nice if we can fix: A lot of changes are really just indentation changes. Is this intentional? If not, can we keep whatever we had before so that the git history won't get overwritten for trivial indentation changes?

yea so indentation changes are due to the fact that I reformatted the pom.xml file in intelliJ

2022-07-13 18:13 UTC, steven-xu-lf commented
> > Minor stuff but would be nice if we can fix: A lot of changes are really just indentation changes. Is this intentional? If not, can we keep whatever we had before so that the git history won't get overwritten for trivial indentation changes?
> 
> yea so the indentation changes are due to the fact that I reformatted both the yaml and pom.xml file in intelliJ but if you want, then i can change it back

@lf-jason-jia ok I just removed the indents in the pom.xml file, I checked the yaml file and they seem to be fine, i guess we do not need to reformat the yaml or pom.xml file

2022-07-14 14:22 UTC, lf-jason-jia approved these changes

2022-07-14 14:22 UTC, merged